version: '3'

services:
  docker:
    image: docker:20.10.17-dind
    privileged: yes
    volumes:
      - certs:/certs
      - type: bind
        source: ${PWD}/certs/domain.crt
        target: '/etc/docker/certs.d/registry:443/ca.crt'

  docker-cli:
    image: docker:20.10.17
    environment:
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
      DOCKER_HOST: tcp://docker:2376
    entrypoint:
      - "tail"
      - "-f"
      - "/dev/null"
    volumes:
      - certs:/certs

  registry:
    image: registry:2.7.0
    expose:
      - 443
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - ${PWD}/certs/domain.crt:/certs/domain.crt
      - ${PWD}/certs/domain.key:/certs/domain.key
    restart: always

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://registry:443
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000

volumes:
  certs: